### ISSUE TITLE
request to be a collaborator

### ISSUE THREAD

**Issue by easella** [nfriedly/nodeunblocker.com#14]
i really wanna be a collaborator

**Comment by nfriedly** [comment]
Hey, sorry for a super-late response; for some reason I wasn't getting notifications from this repo for a while. 

To be a contributor, [make pull requests with helpful code changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) and/or respond to other people's issues and questions.
