### ISSUE TITLE
whatever link i try typing example: youtube.com it dosent work

### ISSUE THREAD

**Issue by Wackolmao** [nfriedly/nodeunblocker.com#30]

**Comment by nfriedly** [comment]
There's probably something wrong, but I can't really say beyond that.  For starters, what do you mean by "it dosent work" - does it give an error message? Does the URL change? Where do you have it hosted? If you're using a static hosting site, such as github pages, that won't work - this requires a node.js backend.

**Comment by Wackolmao** [comment]
> 

i used github codespaces and when i try the link it just says url dosent exist or smth

**Comment by nfriedly** [comment]
Aah, the one time I tried to play with GitHub codespaces, I couldn't get it to work either. At any rate, hosting a server isn't really what they're intended for, so I'm not at all surprised that it doesn't work.

Suffice to say, it's not a supported environment, so I'm going to go ahead and close this
