### ISSUE TITLE
[Feature Request] Change /proxy/ to something else.

### ISSUE THREAD

**Issue by FastestK5** [nfriedly/nodeunblocker.com#33]
Sorry if I sound like a skid while im posting this but; some blockers can block keywords (e.g. proxy) and i'm too stupid to figure out how to manually change it in the code. If not, it fine, ill search the code to figure it out but if this happened it would help a lot.

**Comment by FastestK5** [comment]
Nevermind, I figured it out.

**Comment by nfriedly** [comment]
Just in case anyone else ends up here with the same question, you change it by editing this line:

https://github.com/nfriedly/nodeunblocker.com/blob/220c7d070048fef3113ea1ba78dc56972e747e7c/app.js#L57
