### ISSUE TITLE
Unable to get around IOS screen time restrictions

### ISSUE THREAD

**Issue by Tylerkiller2345** [nfriedly/nodeunblocker.com#4]
IOS has a website filter that looks at parts of the weppage (Mainly title and url) would it be possible to add an option that encrypts the url and changes the title of the webpage?

**Comment by piman51277** [comment]
You can use custom middleware to get around the title.
To scramble the URL, you may need to rewrite/modify a large portion of https://github.com/nfriedly/node-unblocker/blob/master/lib/unblocker.js.
