### ISSUE TITLE
gfn

### ISSUE THREAD

**Issue by ChefTuber** [nfriedly/nodeunblocker.com#44]
it doesn't work, it just redirects to nvidia.com when logging in, which is blocked for me

**Comment by nfriedly** [comment]
What's gfn?

**Comment by ChefTuber** [comment]
geforce now

**Comment by nfriedly** [comment]
Aah, yeah, that's probably never going to work. Significant technical burdens, and double the latency.

**Comment by proplayer919** [comment]
Because GeForce Now connects to a server it will have to connect to the Node Unblocker server as well, which would make all the games laggy and almost unplayable for high-quality games.
