### ISSUE TITLE
YouTube Is Not Working

### ISSUE THREAD

**Issue by Tenakskd** [nfriedly/nodeunblocker.com#47]
/proxy/https:/www.youtube.com/shorts/V6gzUXPucH8?pbjreload=101

error Code : Error retrieving video info
Help me

**Comment by Tenakskd** [comment]
When I embed a video and try to open it, I get an error, is there any way to get rid of that?

**Comment by nfriedly** [comment]
Yeah, it looks like youtube is detecting and blocking the proxy. Not sure if there's anything I can do about that :(

**Comment by Tenakskd** [comment]
Sorry
